[theme]
base = "light"
primaryColor = "#FF69B4"         # アクセントカラー（例：薄いピンク）
backgroundColor = "#FFF0F5"      # メイン画面背景：薄いピンク
secondaryBackgroundColor = "#FFF5EE"  # サイドバー背景：柔らかい黄色
textColor = "#262730"
font = "sans serif"
